runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

env_variables:
  FLASK_ENV: "production"

handlers:
- url: /static
  static_dir: frontend/static

- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic 